name: Build Next.js web application
on: push
jobs:
  build-project:
    name: Build Next.js project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload site content
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: .next/
  distribute-project:
    name: Distribute Next.js project to GitHub Releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    needs: build-project
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip

      - name: Create GitHub release
        id: new-test-release-cosign
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Upload asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new-test-release-cosign.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.0.3

      - name: Sign the Release Artifact
        id: sign-display-output
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          echo 'y' | cosign sign-blob site.zip --bundle cosign-site-v${{ github.run_number }}.bundle
          
      - name: Verify the Release Artifact
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify-blob site.zip --bundle cosign-site-v${{ github.run_number }}.bundle --certificate-identity=https://github.com/Miranlfk/app-release-pub/.github/workflows/release.yml@refs/heads/main --certificate-oidc-issuer=https://token.actions.githubusercontent.com
    
      - name: Create Verify Text File
        run: 'echo "cosign verify-blob site-v${{ github.run_number }}.zip --bundle cosign-site-v${{ github.run_number }}.bundle --certificate-identity=https://github.com/Miranlfk/app-release-pub/.github/workflows/release.yml@refs/heads/main --certificate-oidc-issuer=https://token.actions.githubusercontent.com" > verify.txt'
        
      - name: Upload Signature to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new-test-release-cosign.outputs.upload_url }}
          asset_path: ./verify.txt
          asset_name: verify-site-v${{ github.run_number }}.txt
          asset_content_type: application/octet-stream
          
      - name: Upload Bundle to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new-test-release-cosign.outputs.upload_url }}
          asset_path: ./cosign.bundle
          asset_name: cosign-site-v${{ github.run_number }}.bundle
          asset_content_type: application/octet-stream         
